configuration:
  - Debug
  - Release

platform: Any CPU

environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

cache:
  - '%USERPROFILE%\.nuget\packages'

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build -c Release

after_build:
  - dotnet pack -c Release src\OpenPr0gramm\OpenPr0gramm.csproj

test_script:
  - dotnet test "src\OpenPr0gramm.Tests" -c %CONFIGURATION%

artifacts:
  - path: src\OpenPr0gramm\bin\Release\*.nupkg
